package/mpc: fix to link in CYGWIN
The symbols aren't exported correct in CYGWIN with the errors to
build gcc initial:

 /tmp/ccRDZ5Sc.o:conftest.c:(.text.startup+0x91): undefined reference to `_imp__mpc_init2'
 /tmp/ccRDZ5Sc.o:conftest.c:(.text.startup+0xb2): undefined reference to `_imp__mpc_set_ui_ui'
 /tmp/ccRDZ5Sc.o:conftest.c:(.text.startup+0xc7): undefined reference to `_imp__mpc_cosh'
 /tmp/ccRDZ5Sc.o:conftest.c:(.text.startup+0xe0): undefined reference to `_imp__mpc_pow'
 /tmp/ccRDZ5Sc.o:conftest.c:(.text.startup+0xf5): undefined reference to `_imp__mpc_acosh'
 /tmp/ccRDZ5Sc.o:conftest.c:(.text.startup+0xfe): undefined reference to `_imp__mpc_clear'

http://lists.gforge.inria.fr/pipermail/mpc-discuss/2011-April/000895.html
explains the reason and fixed the problem to remove __MPC_WITHIN_MPC for
the symbols.

Change-Id: I693208f0a663f73e9e67f08491a7ddbb0416ac96